api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import ClienteApi, PedidoApi, RestauranteApi, ProdutoApi

urlpatterns = {
    
    url(r'cliente_api/', ClienteApi.as_view(), name='cliente_api'),
    url(r'pedido_api/', PedidoApi.as_view(), name='pedido_api'),
    url(r'restaurante_api/', RestauranteApi.as_view(), name='restaurante_api'),
    url(r'produto_api/', ProdutoApi.as_view(), name='produto_api'),
    
}

urlpatterns = format_suffix_patterns(urlpatterns)

cliente/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import *
from . import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('cliente', views.Cliente_list, name='cliente'),
    path('pedido', views.Pedido_list, name='pedido'),
    path('cliente_edit/<int:pk>', views.Cliente_edit, name='cliente_edit'),
    path('cliente_delete/<int:pk>', views.Cliente_delete, name='cliente_delete'),
    path('pedido_edit/<int:pk>', views.Pedido_edit, name='pedido_edit'),
    path('pedido_delete/<int:pk>', views.Pedido_delete, name='pedido_delete'),
    path('cliente_print_pdf', views.Cliente_Print_pdf, name='cliente_print_pdf'),
    path('pedido_print_pdf', views.Pedido_Print_pdf, name='pedido_print_pdf'),
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diamanfood/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('cliente.urls'),name='cliente'),
    path('restaurantes/', include('restaurantes.urls'),name='restaurantes'),
    path('api/', include('api.urls'),name='api'),
]

cliente/models.py
from django.db import models
from restaurantes.models import Produto

GENERO_CHOICE = (
    ('M','Masculino'),
    ('F','Feminino'),
    ('N', 'Não Declarado'),
)


class Cliente(models.Model):
    nome = models.CharField(
        'Nome', max_length=120)
    genero = models.CharField(
        'Genero', max_length=2, choices=GENERO_CHOICE)
    endereco = models.CharField(
        'Endereço', max_length=80, blank=True, null=True)
    cidade = models.CharField(
        'Cidade', max_length=20, blank=True, null=True)
    idade = models.CharField(
        'Idade', max_length=20)
    aniversario = models.DateField(
        'Aniversário', blank=True, null=True)
    status = models.BooleanField(
        'Status', default=True)
    
    
         

    class Meta:

        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return self.nome


class Pedido(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.CharField(
        'Quantidade', max_length=2, blank=True, null=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    
    class Meta:

        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return self.produto        
        

cliente/forms.py
from django import forms
from cliente.models import *


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        field = '__all__'
        exclude = ()

class PedidoForm(forms.ModelForm):

    class Meta:
        model = Pedido
        field = '__all__'
        exclude = ()

cliente/views.py
from django.shortcuts import render
from .forms import ClienteForm,PedidoForm
from .models import Cliente, Pedido
from django.contrib import messages
from django.shortcuts import render, redirect, get_list_or_404
from weasyprint import HTML, CSS
from django.http import HttpResponse
from django.template.loader import render_to_string, get_template
from django.core.files.storage import FileSystemStorage
def teste(request):

    nome = "André Almeida"

    soma = 4+4
    
    context = { 
        'nome' : nome,
        'soma' : soma,  
    }

    return render(request, 'cliente/teste.html', context)

def home(request):

    context = {

    }

    return render(request, 'cliente/home.html', context)

def Cliente_list(request):
    ##ORM DE SELECT NO DNJANGO
    cliente = Cliente.objects.filter()
    

    if request.method == 'POST':

        form = ClienteForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,'Cliente cadastrado com sucesso')
            return redirect('cliente')
        context = {
            
            'form': form
        }

        return render(request, 'legacy/cliente.html', context)

    form = ClienteForm()

    context = {
        'cliente' : cliente,
        'form': form
    }
    return render(request, 'cliente/cliente.html', context)

def Pedido_list(request):
    ##ORM DE SELECT NO DNJANGO
    pedido = Pedido.objects.filter()
    

    if request.method == 'POST':

        form = PedidoForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,'Pedido cadastrado com sucesso')
            return redirect('pedido')
        context = {
            
            'form': form
        }

        return render(request, 'legacy/pedido.html', context)

    form = PedidoForm()

    context = {
        'pedido' : pedido,
        'form': form
    }
    return render(request, 'cliente/pedido.html', context)

def Cliente_edit(request,pk):

    cliente = Cliente.objects.get(pk=pk)

    form = ClienteForm(request.POST or None, instance=cliente)
  
    if form.is_valid():
        form.save()
        messages.success(request,'Cliente editado com sucesso')
        return redirect('cliente')

    context = {
        'form':form,
        'id':cliente.id
    }

    return render(request,'cliente/cliente_edit.html', context)

def Cliente_delete(request,pk):

    cliente = Cliente.objects.get(pk=pk)
    cliente.delete()
    messages.error(request,'Cliente removido com sucesso')
    return redirect('cliente')

def Pedido_edit(request,pk):

    pedido = Pedido.objects.get(pk=pk)

    form = PedidoForm(request.POST or None, instance=pedido)
  
    if form.is_valid():
        form.save()
        messages.success(request,'Pedido editado com sucesso')
        return redirect('pedido')

    context = {
        'form':form,
        'id':pedido.id
    }

    return render(request,'cliente/pedido_edit.html', context)

def Pedido_delete(request,pk):

    pedido = Pedido.objects.get(pk=pk)
    pedido.delete()
    messages.error(request,'Pedido removido com sucesso')
    return redirect('pedido')

def Cliente_Print_pdf(request):

    cliente = Cliente.objects.all()
    
    context = {
        'cliente' : cliente,
    
    }
    html_string = render_to_string('cliente/cliente_print.html', context)
    html = HTML(string=html_string, base_url=request.build_absolute_uri())
    html.write_pdf(target='/tmp/cliente_print_pdf.pdf')


    fs = FileSystemStorage('/tmp')

    with fs.open('cliente_print_pdf.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = "inline; filename='print.pdf'"
        
        return response

    return response

    return render(request, 'cliente/cliente_print.html', context)

def Pedido_Print_pdf(request):

    pedido = Pedido.objects.all()
    
    context = {
        'pedido' : pedido,
    
    }
    html_string = render_to_string('cliente/pedido_print.html', context)
    html = HTML(string=html_string, base_url=request.build_absolute_uri())
    html.write_pdf(target='/tmp/pedido_print_pdf.pdf')


    fs = FileSystemStorage('/tmp')

    with fs.open('pedido_print_pdf.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = "inline; filename='print.pdf'"
        
        return response

    return response

    return render(request, 'cliente/pedido_print.html', context)

cliente/templates/cliente/base.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>DiamanFood</title>
        <link rel="shortcut icon" href="{% static '/img/logo_ico.png' %}"> 
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">    <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'adminLTE/css/AdminLTE.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'adminLTE/css/skins/skin-yellow.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/checkbox.css' %}" >
        <!-- iCheck -->
        <link rel="stylesheet" type="text/css" href="{% static 'iCheck/square/blue.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/botoes.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'datatables/css/dataTables.bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/usuario.css' %}">
        <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
        
    
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </head>
    <body class="hold-transition skin-yellow sidebar-mini">
    <div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="{% url 'home' %}" class="logo">
         
        <span class="logo-mini">DF</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><strong><em>Diaman</em></strong>Food</span>
        
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

<div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          
          <!-- Notifications: style can be found in dropdown.less -->
          
          {% if ntarefas > 0 %}
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">{{ ntarefas }}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">Voce tem {{ ntarefas }} tarefas para hoje</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  {% for n in notificacao %}
                  <li>
                    <a href="#">
                      <i class="fa fa-warning text-yellow"></i> {{ n.Tarefa }}
                    </a>
                  </li>
                {% endfor %}
    
                  
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="{% url 'tarefaexec' %}">Ver Todas</a></li>
            </ul>
          </li>
          {% endif %}
         
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {% if request.user.Foto != '' %}
                <img src="{{ request.user.Foto.url }}" class="user-image" alt="User Image">
                {% else %}
                <img src="{% static 'img/nophoto.jpg' %}" class="user-image" alt="User Image">
                {% endif %}
                <span class="hidden-xs">{{ request.user.Nome }}</span>
                </a>
                <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                    {% if request.user.Foto != '' %}
                    <img src="{{ request.user.Foto.url }}" class="img-circle" alt="User Image">
                    {% else %}
                    <img src="{% static 'img/nophoto.jpg' %}" class="img-circle" alt="User Image">
                {% endif %}
                    <p>
                    {{ request.user.Nome }}
                    {% if request.user.Funcao == "PROP"  %}
                    <small>PROPRIETÁRIO</small>
                    {% elif request.user.Funcao == "SUPM" %}
                    <small>SUPERVISOR MASTER</small>
                    {% elif request.user.Funcao == "SUPV" %}
                    <small>GERENTE</small>
                    {% elif request.user.Funcao == "VEND" %}
                    <small>CONSULTOR</small>
                    {% endif %}
                    </p>
                </li>
                <!-- Menu Body -->
               
                <!-- Menu Footer-->
                <li class="user-footer">
                    <div class="pull-left">
                    <a href="#" class="btn btn-default btn-flat">Meus Dados</a>
                    </div>
                    <div class="pull-right">
                    <a href="#" class="btn btn-default btn-flat">Sair</a>
                    </div>
                </li>
                </ul>
            </li>
            </ul>
        </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
        <!-- Sidebar user panel -->

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MENU</li>
            <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> <span>Início</span></a></li>
            <li class="treeview">
            <a href="#">
                <i class="fa fa-users"></i>
                <span>Cliente</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'cliente'%}"><i class="fa fa-users"></i> Clientes</a></li>
                <li><a href="{% url 'pedido'%}"><i class="fa fa- fa-check"></i> Pedidos</a></li>
              </ul>
            </li>
            <li class="treeview">
            <a href="#">
                <i class="fa  fa-fire"></i>
                <span>Restaurante</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu" >
                <li><a href="{% url 'restaurante'%}"><i class="fa fa-cutlery"></i> Restaurantes</a></li>
                <li><a href="{% url 'produto'%}"><i class="fa fa-coffee"></i> Produtos</a></li>
            </ul>
        </li>
        </ul>
           
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        
        {% block content %}
            
        <!-- Content Header (Page header) -->
        <section class="content-header">
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ message }}
            </div>
        {% endfor %}
        {% endif %}
        <h1>
            
        {% block content-header %}
            Dashboard <small>Painel de controle</small>        
        {% endblock content-header %}
                

        </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            
        <!-- Small boxes (Stat box) -->
        <div class="row">
            
            {% block content-main %}
                
            {% endblock content-main %}
            <!-- ./col -->
        </div>
        <!-- /.row -->

        </section>

        {% endblock content %}
        <!-- /.content -->
    </div>

    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
        <b>Version</b> 0.1
        </div>
        <strong>Copyright &copy; 2014-2016 <a href="https://www.minasvale.com.br">MinasVale</a>.</strong> Todos os direitos reservados</footer>


    <script src={% static 'jquery/jquery.min.js' %}></script>
    <script src={% static 'jquery-slimscroll/jquery.slimscroll.min.js' %}></script>
    <script src={% static 'fastclick/fastclick.js' %}></script>
    <script src={% static 'adminLTE/js/adminlte.min.js' %}></script>
    <script src={% static 'select2/js/select2.min.js' %}></script>
    <script src={% static 'datatables/js/jquery.dataTables.min.js' %}></script>
    <script src={% static 'datatables/js/dataTables.bootstrap.min.js' %}></script>
    <script src={% static 'bootstrap/js/bootstrap.min.js' %}></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script> -->
    <script src={% static 'chart.js/Chart.js' %}></script>
    <script src={% static 'inputmask/dist/min/jquery.inputmask.bundle.min.js' %}></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.js"></script>
  
    {% block extraJS %}{% endblock extraJS %}
        

</body>
</html>

cliente/templates/cliente/cliente.html
{% extends "cliente/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block content-header %}

<i class="fa fa-users "> </i> Clientes
<small>Cadastrar e consultar</small>


{% endblock content-header %}


{% block content-main %}


<div class="col-xs-12">


    <div class="box">
        <div class="box">
            <div class="box-header">
                <button type="button" class="ui-button" data-toggle="modal" data-target="#exampleModal51">Cadastrar Cliente
                </button>
            </div>

            <div class="box-header">
                <h3 class="box-title">Clientes cadastrados no sistema</h3>
            </div>


            <div class="box-body">
                <table id="tabela" class="table table-bordered table-striped" style="font-size: 13px">
                    <thead>
                    <tr>
                        <th>Nome Cliente</th>
                        <th>Endereço</th>
                        <th>Cidade</th>
                        <th>Sexo</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for u in cliente %}
                    <tr>
                            <td >{{ u.nome }}</td>
                            <td >{{ u.endereco }}</td>
                            <td >{{ u.cidade }}</td>
                            <td >{{ u.get_genero_display }}</td>
                           

                        <td>
                            <a href="{% url 'cliente_edit' u.id%}" data-toggle="modal" data-target="#modalEdit{{u.id}}">
                                <button type="button" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i></i></button>
                            </a>
                            <a href="#" data-toggle="modal" data-target="#modalDelete{{u.id}}">
                                <button type="button" class="btn btn-xs btn-danger" id="confirm"><i class="fa fa-close"></i></button>
                            </a>
                        </td>

                    </tr>

                    <div class="modal fade" id="modalEdit{{u.id}}" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <!--Modal continua no arquivo cliente_edit.html-->
                            </div>
                        </div>
                    </div>

                    <div class="modal fade" id="modalDelete{{ u.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    Confirmação de Exclusão
                                </div>
                                <div class="modal-body">
                                    <form method="GET">
                                        Tem certeza?
                                    
                                        <div class="modal-footer">
                                            <button  type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            <a href="{% url 'cliente_delete' u.id%}" class="btn btn-danger">Excluir</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}


                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>

        <div class="modal fade" id="exampleModal51" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                      </button>
                      <h4 class="modal-title" id="exampleModalLabel">Cadastrar Clientes</h4>
                  </div>
                  <div class="modal-body">
                      <form method="POST">
                          {% csrf_token %}
                          {{ form|bootstrap }} 
                          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                          <button type="submit" class="btn btn-success">Cadastrar</button>
                      </form>
                  </div>
      
              </div>
          </div>
      </div>


{% endblock content-main %}


{% block extraJS %}

<script>
        
           
        
        
        $(document).ready(function () {

            $('#tabela').DataTable({
                "language": {
                    "url": "{% static 'datatables/Portuguese-Brasil.json' %}"
                },
                stateSave: true,
            });

        });


</script>


{% endblock extraJS %}

cliente/templates/cliente/cliente_edit.html
{% load staticfiles %}
{% load bootstrap %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="exampleModalLabel">Editar Usuário</h4>
 </div>   

<div class="modal-body">
     
    <form method="POST" action="{% url 'cliente_edit' id %}">
        {% csrf_token %}
        {{ form|bootstrap }} 
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-success">Alterar</button>
    </form>  


</div>

cliente/templates/cliente/cliente_print.html
<!DOCTYPE html>
<html>
        <style>
                table {
                  font-family: arial, sans-serif;
                  border-collapse: collapse;
                  width: 100%;
                }
                
                td, th {
                  border: 1px solid #dddddd;
                  text-align: left;
                  padding: 8px;
                }
                
                tr:nth-child(even) {
                  background-color: #dddddd;
                }
                </style>
<head>
<table id="tabela" class="table table-bordered table-striped" style="font-size: 13px">
    <thead>
    <tr>
        <th>Nome Cliente</th>
        <th>Endereço</th>
        <th>Cidade</th>
        <th>Sexo</th>
    </tr>
    </thead>
    <tbody>

    {% for u in cliente %}
    <tr>
            <td >{{ u.nome }}</td>
            <td >{{ u.endereco }}</td>
            <td >{{ u.cidade }}</td>
            <td >{{ u.get_genero_display }}</td>
    </tr>
    {% endfor %}

</table>
</body>
</html>

cliente/templates/cliente/home.html
{% extends "cliente/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load static %}


{% block content-header %}

    Vendas<small>Home</small>
    
    
{% endblock content-header %}

{% block content-main %}
<section class="content"> 
<div class="row">
<div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>6</h3>
            <p>Clientes Cadastrados</p>
          </div>
          <div class="icon">
            <i class="ion ion-bag"></i>
          </div>
          <a href="{% url 'cliente_print_pdf' %}" class="small-box-footer">Imprimir Lista <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>

      <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>4</h3>
              <p>Restaurantes Cadastrados</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="{% url 'restaurante_print_pdf' %}" class="small-box-footer">Imprimir Lista <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
              <div class="inner">
                <h3>3</h3>
  
                <p>Pedidos Feitos</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="{% url 'pedido_print_pdf' %}" class="small-box-footer">Imprimir Relatorio <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
      </div>
      <div class="row">
      <div class="col-12 col-md-8">
        <div class="box box-danger" >
            <div class="box-header with-border">
                <h3 class="box-title">Clientes por Cidade</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>

        <canvas id="myChart" style="height: 235px; width: 470px;" width="470" height="235"></canvas>
      </div>
    </div>
      <div class="col-6 col-md-4">
      <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Ultimos Restaurates Cadastrados</h3>

            <div class="box-tools pull-right">
              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
              </button>
              <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
          </div>
          <!-- /.box-header -->
          {% for u in restaurante %}
          <div class="box-body">
            <ul class="products-list product-list-in-box">
              <li class="item">
                <div class="product-info">
                  <a href="javascript:void(0)" class="product-title">{{ u.nome }}
                </div>
              </li>
              <!-- /.item -->
              <li class="item">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title">Samsung TV
                  </div>
                </li>
              <!-- /.item -->
              <li class="item">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title">Samsung TV
                  </div>
                </li>
              <!-- /.item -->
              <li class="item">
                  <div class="product-info">
                    <a href="javascript:void(0)" class="product-title">Samsung TV
                  </div>
                </li>
            </ul>
          </div>
          {% endfor %}
          <!-- /.box-body -->
          <div class="box-footer text-center">
            <a href="{% url 'restaurante' %}" class="uppercase">Ver Todos Restaurantes</a>
          </div>
          <!-- /.box-footer -->
        </div>
        </div>
    </div>
</div>   
</div> 
</section>  
{% endblock content-main %}

{% block extraJS %}
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'doughnut',

    // The data for our dataset
    data: {
        labels: ["Diamantina", "Gouveia", "Datas"],
        datasets: [{
            label: "My First dataset",
            backgroundColor: ['#001F3F','#605ca8','#D81B60'],
            data: [10, 5, 2],
        }]
    },

    // Configuration options go here
    options: {}
});
    </script>


{% endblock extraJS %}
    

cliente/templates/cliente/pedido_edit.html
{% load staticfiles %}
{% load bootstrap %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="exampleModalLabel">Editar Pedido</h4>
 </div>   

<div class="modal-body">
     
    <form method="POST" action="{% url 'pedido_edit' id %}">
        {% csrf_token %}
        {{ form|bootstrap }} 
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-success">Alterar</button>
    </form>  


</div>